import { AspectRatio, Box, Center, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import EnterButton from "../components/enterButton";
import { Dancing_Script } from "@next/font/google";
import { Inter } from '@next/font/google'

const dancingScript = Dancing_Script();
const inter = Inter();

const HomePage = () => {
    return (
        <>
            <Head>
                <title>Exotic Plays</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Flex height={'70vh'} alignItems={'center'} justifyContent={'center'}>
                <Text mr='7' fontFamily={inter.className} fontSize='125px' fontWeight={'bold'}>Exotic</Text>
                <div style={{ fontSize: '125px', textShadow: '0 0 10px rgba(255, 0, 0, 0.5), 0 0 20px rgba(255, 0, 0, 0.4), 0 0 30px rgba(255, 0, 0, 0.3)' }}
                    className={dancingScript.className}>
                    <p> Plays</p>
                </div>
            </Flex>

            <Box height={"100vh"} width={'100%'} position={"relative"}>
                <AspectRatio position="absolute" height={"100vh"} width={'100%'} ratio={1.75} zIndex={1}>
                    <video
                        title='home'
                        autoPlay
                        muted
                        loop
                        style={{ width: '100%', height: '100%', objectFit: 'fill' }}
                    >
                        <source src="/videos/home.mp4" type="video/mp4" />
                    </video>
                </AspectRatio>
                <Box zIndex={2} style={{ position: "absolute", top: '80%', left: '50%', transform: "translate(-50%, -50%)" }}> <EnterButton /> </Box>
            </Box></>
    );
}

export default HomePage;