import { Box, Center, Text } from "@chakra-ui/react";
import Head from "next/head";
import EnterButton from "../components/enterButton";
//move stylesheet to Document tag instead of Head

const HomePage = () => {
    return (
        <Box height={'100vh'} width={'100%'} backgroundColor={'purple.100'}>
        
            <Head>
                <title>Exotic Plays</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="C:\Users\Pranik\ExoticPlays\frontend\public\styles\global.css" />
            </Head>
            <Center>
                <Text>Exitcccccccc</Text>
                <EnterButton /> 
            </Center>
        </Box>
    );
}

export default HomePage;