import Head from 'next/head'
import type { NextPage, NextPageContext } from "next";
import { getSession } from "next-auth/react";
import { Inter } from '@next/font/google'
import { Box} from '@chakra-ui/react';
import EnterButton from '../components/enterButton';

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {

  return (
    <Box h='50vh' backgroundColor ='yellow.100'>
      <Head>
        <title>Exotic Plays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Exotic Playsssssssss</h1>
      <p>Come play w some baddies</p>
      <center>
        <div>
          <EnterButton />  
        </div>
      </center>
    </Box>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  return {
    props: {
      session
    }
  };
};

export default Home;
